### ISSUE TITLE
needs update from the TheMuppets repository

### ISSUE THREAD

**Issue by nezorflame** [AICP/proprietary_vendor_oneplus#1]
Please either merge the latest changes from https://github.com/TheMuppets/proprietary_vendor_oneplus repo or use it for oneplus3 builds.
Right now it contains new blobs from 4.0.3 which are supposedly better for the camera quality.
Also using these enables the OnePlus camera port from siankatabg to work.

**Comment by SubhrajyotiSen** [comment]
The next builds will have the updated blobs
